services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=callofduty
      - DB_USERNAME=callofduty
      - DB_PASSWORD=secret
    command: sh -c "chown -R www-data:www-data storage bootstrap/cache storage/logs && php-fpm"

  vite:
    image: node:22
    container_name: vite_frontend
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: callofduty
      MYSQL_USER: callofduty
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:1.25
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_data:
    driver: local
